server:
  port: 9099
  servlet:
    context-path: /RollCall
  max-http-header-size: 8192
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host:3306/RollCall
    username: root
    password: 
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
